---
# Переменные по умолчанию для роли
apache_package: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
apache_service: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
apache_user: "{{ 'www-data' if ansible_os_family == 'Debian' else 'apache' }}"
web_root: "/var/www/html"